import type { NextPage } from "next";
import RequestQuoteIcon from "@mui/icons-material/RequestQuote";
import CurrencyYenIcon from "@mui/icons-material/CurrencyYen";
import CurrencyExchangeIcon from "@mui/icons-material/CurrencyExchange";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

import Head from "next/head";
import { trpc } from "../utils/trpc";
import { numberWithCommas } from "../utils/tools";
import { Skeleton } from "@mui/material";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["guest.dashboard"]);
  console.log(data?.chartPayload);
  if (isLoading) {
    return (
      <div className="flex flex-col gap-5 lg:grid grid-cols-3">
        <Skeleton variant="rounded" height={80} />
        <Skeleton variant="rounded" height={80} />
        <Skeleton variant="rounded" height={80} />
        <div className="bgPaper lg:col-span-3 ">
          <Skeleton variant="rounded" height={400} />
        </div>
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>SEMBA | 首頁</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col gap-5 lg:grid grid-cols-3">
        <div className="bgPaper">
          <h3 className="text-stone-500 ">
            <RequestQuoteIcon /> 成交總金額
          </h3>
          <h2 className="text-emerald-500">$ {numberWithCommas(data?.aSum)}</h2>
        </div>

        <div className="bgPaper">
          <h3 className="text-stone-500">
            <CurrencyYenIcon />
            利潤
          </h3>
          <h2 className="text-red-500">$ {numberWithCommas(data?.pSum)}</h2>
        </div>
        <div className="bgPaper">
          <h3 className="text-stone-500">
            <CurrencyExchangeIcon />
            總支出
          </h3>
          <h2 className="text-pink-500">$ {numberWithCommas(data?.cSum)}</h2>
        </div>
        <div className="bgPaper lg:col-span-3 w-full md:h-72 lg:h-96">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart
              margin={{
                top: 5,
                right: 30,
                left: 20,
                bottom: 5,
              }}
              width={500}
              height={400}
              data={data?.chartPayload}
            >
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="id" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Line
                type="monotone"
                dataKey="total"
                stroke="#8884d8"
                activeDot={{ r: 8 }}
              />
              <Line type="monotone" dataKey="cost" stroke="#82ca9d" />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
    </>
  );
};

export default Home;
