import type { NextPage } from "next";

import Head from "next/head";



const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Dashboard-home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>還在施工中... ...</>

    </>
  );
};

export default Home;
