INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("復華","復華廣告有限公司","00000000");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("富台","富台機械開發建設有限公司","00000016");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("泰煜","泰煜建材股份有限公司","00000022");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("茂盛","茂盛工程有限公司（同名）","00000037");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("一成","一成運輸報關股份有限公司","00000206");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("三合","三合益煤油有限公司","00000228");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("九州","九州建設股份有限公司","00000233");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("八達","八達倉儲通運有限公司","00001508");