INSERT INTO company(c_name ,c_title ,c_tax ) 
VALUES
("聚思怡","台灣聚思怡股份有限公司","90443462")
("玉登","玉登室內裝修有限公司","16000287"),
("LINTEC","琳得科先進科技股份有限公司","70407360"),
("大金空調","大金冷氣空調有限公司","25048522")
("興昇","興昇科技股份有限公司","24451546"),
("創意家具","創意辦公家具有限公司","28627623"),
("悠尼淇","悠尼淇照明股份有限公司","80124806"),
("富銘地板","富銘有限公司","15863623"),
("和印紙","和印紙業股份有限公司","22605003"),
("神預備","神預備股份有限公司","83182651"),
("丞石","丞石建築開發有限公司","53325647")

INSERT INTO Company(c_name ,c_title ,c_tax ) VALUES("聚思怡","台灣聚思怡股份有限公司","90443462"),
("LINTEC","琳得科先進科技股份有限公司","70407360"),
("大金空調","大金冷氣空調有限公司","25048522"),
("興昇","興昇科技股份有限公司","24451546"),
("創意家具","創意辦公家具有限公司","28627623"),
("悠尼淇","悠尼淇照明股份有限公司","80124806"),
("富銘地板","富銘有限公司","15863623"),
("和印紙","和印紙業股份有限公司","22605003"),
("神預備","神預備股份有限公司","83182651"),
("丞石","丞石建築開發有限公司","53325647");

-- ("","",""),






INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("富台","富台機械開發建設有限公司","00000016");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("泰煜","泰煜建材股份有限公司","00000022");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("茂盛","茂盛工程有限公司（同名）","00000037");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("一成","一成運輸報關股份有限公司","00000206");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("三合","三合益煤油有限公司","00000228");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("九州","九州建設股份有限公司","00000233");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("八達","八達倉儲通運有限公司","00001508");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("復華","復華廣告有限公司","00000000");


INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("大道汽車","大道汽車股份有限公司","00026607");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("大基報關","大基報關通運股份有限公司","00022905");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("福興園","上海福興園菜館股份有限公司","00021808");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("上海煤氣","上海煤氣有限公司","00021407");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("三和","三和興煤氣股份有限公司","00016805");
INSERT INTO company(c_name ,c_title ,c_tax ) VALUES("立人","立人汽車股份有限公司","00012104");